/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ls_jnilib_jni_JNITest */

#ifndef _Included_com_ls_jnilib_jni_JNITest
#define _Included_com_ls_jnilib_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ls_jnilib_jni_JNITest
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ls_jnilib_jni_JNITest_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
